apiVersion: v1
kind: Pod
metadata:
  name: mandelbrot
  namespace:
  labels:
    run: nginx
    app: webserver
spec:
  containers:
  - name: main
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
  - name: supporting
    image: emedves/mandelbrot2png:v5
    volumeMounts:
    - name: html
      mountPath: /output
  volumes:
  - name: html
    emptyDir: {}
