apiVersion: v1
kind: Pod
metadata:
  name: mandelbrot4
  namespace:
  labels:
    key: value
spec:
  containers:
  - name: mandelbrot
    image: emedves/mandelbrot2png:v4
    imagePullPolicy: Always
    volumeMounts:
    - name: html
      mountPath: /output
  volumes:
  - name: html
    emptyDir: {}
